### ISSUE TITLE
Skills won't increment over 6-

### ISSUE THREAD

**Issue by jephkay23** [dmdorman/hero6e-foundryvtt#25]
No matter what I do, I cannot get a skill over 6-.

**Comment by dmdorman** [comment]
I believe I fixed this in the most recent release, though I'm not 100% certain all the math is correct

**Comment by techogre** [comment]
Still an issue in 2.0.5. Now the skill will display correctly but still rolls as if it's 6-.

**Comment by dmdorman** [comment]
Please try the most recent release. Note this is still not fixed for skills derived from the 'power' type item as that item type needs a rework

**Comment by jephkay23** [comment]
Actually, I have! Works great now. I feel like I could run my Fantasy HERO game if the character sheet form were scrollable or able to be resized. 
I keep checking for updates and I was not disappointed by the latest iteration. It's getting there! 
    On Wednesday, March 8, 2023 at 09:25:25 PM EST, dmdorman ***@***.***> wrote:  
 
 


Please try the most recent release. Note this is still not fixed for skills derived from the 'power' type item as that item type needs a rework

**Comment by techogre** [comment]
Can confirm. Works with added skills, but not with power derived skills.

**Comment by dmdorman** [comment]
I believe this should work for power derived skills as of Version 2.1.0

**Comment by techogre** [comment]
Confirmed. Working in 2.1.0
