### ISSUE TITLE
TakeRecovery penalty x2

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#2613]
<img width="184" height="156" alt="Image" src="https://github.com/user-attachments/assets/3f4b0933-51cf-4a2a-8b44-f22ecc8bd0cc" />

<img width="853" height="126" alt="Image" src="https://github.com/user-attachments/assets/57ae1e28-a7e2-4f69-9191-c204caa3c093" />

TakeRecovery is not clearing during onStart

**Comment by aeauseth** [comment]
The duration of the TakeRecovery penalty wasn't set properly, so it never expired.  Because it wasn't a temporary effect, you could end up with more than one TakeRecovery penalty (ActiveEffect).  Both of these issues have been fixed.

**Comment by phBalance** [comment]
Still not expiring properly. It's expiring at the start of the character's next phase (so they remain at 1/2 DCV for the whole time). Is that actually correct? The rules say that they're at 1/2 DCV while "recovering" but the recovery happens at the bottom of the segment.

We still have problems with taking a recovery:
* The recovery is happening instantaneously. It should only happen at the end of the segment if they haven't used END or taken damage.
* We allow constant powers to be active in 6e (6e is nasty it seems)
