### ISSUE TITLE
After importing HDC files can't see entire list

### ISSUE THREAD

**Issue by RPMiller1** [dmdorman/hero6e-foundryvtt#27]
After I've imported an HDC file, and go to any page, I can only see three items and there is no scroll bar. Am I missing something?

**Comment by dmdorman** [comment]
What version are you on? 

I think I addressed this in the most recent release

**Comment by RPMiller1** [comment]
Ah, I checked and I'm still on 2.0. I thought I updated. Let me try that again. Thanks for the quick fix and responses!

**Comment by RPMiller1** [comment]
I've updated to 2.0.2 and I still have the same issue. At most I see 4 skills and there is no scroll bar to be able to see the rest.

**Comment by dmdorman** [comment]
Sorry about that. Thought that release had my most recent changes. Please try 2.0.3

**Comment by dmdorman** [comment]
@RPMiller1 have you been able to get this to work?

**Comment by RPMiller1** [comment]
It is giving me a scrollbar, which is good; however, it doesn't appear to be handling the skills properly. If you look at the Acrobatic Ape Man for example, it looks like the upload isn't handling lists properly and is dropping skills in lists. Also, levels are showing up as rolls instead of adders, but that may just be a function of the way the skills work?
![image](https://user-images.githubusercontent.com/29924417/223944430-a92f27bf-8e5d-402f-a972-4916712f7929.png)
![image](https://user-images.githubusercontent.com/29924417/223944750-29107868-2507-41fd-a8ce-30b3102723f4.png)

**Comment by dmdorman** [comment]
Looks like there was some logic that was leaving those skills off the actor sheet. Should be fixed in 2.0.7

**Comment by RPMiller1** [comment]
Well, just tested 2.0.7 and I'm seeing problems. No idea how things broke, but it is no longer displaying anything from the HDC file unless I upload it again, and when I do, it is iffy especially the skill list. I see all the skills flash on the screen being written to a single line and then overwritten and then nothing is displayed. All the other tabs have similar problems with things not displaying. No idea what might have broken.

**Comment by dmdorman** [comment]
That's very odd. Is this on a particular character?

Could you send a screenshot of the behavior?

**Comment by RPMiller1** [comment]
It's hard to capture in a screenshot since it goes insanely fast. It was definitely happening on the Ape Man and Mercurial Speedster. I didn't check all the characters, but I can check tomorrow.

**Comment by dmdorman** [comment]
When you upload it deletes a lot of the items before adding them back. I can't remember off the top of my head if its all items or not. So maybe that's what you're seeing? 

I'm wondering mostly what everything being on a single line looks like and which tabs are missing stuff?

Do you see any error messages pop up on the screen?

**Comment by techogre** [comment]
It seems to be working in 2.10
